name: "Nix CI"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Check flake
        run: nix flake check --no-build
      - name: Evaluate system configuration
        run: nix nix eval .#nixosConfigurations.homeserver.config.system.build.toplevel.drvPath
